import Head from 'next/head'
import Image from 'next/image'
import Footer from './Footer'
import Typewriter from 'typewriter-effect'
import Navbar from './Navbar.js'
import About from './About'
import Work from './Work'
import { motion, useAnimation } from "framer-motion";


import { useInView } from "react-intersection-observer";

import { useEffect } from "react";
import Lottie from 'react-lottie' 
// import animationData from '/Users/ananthakrishnan/Library/Mobile Documents/com~apple~CloudDocs/Documents/Code/Portfolio/anantha/24972-hi.json;'
import animationData from'./lottie/Hi.json'

export default function Home() {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    clickToPause:false,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    }
  };

  return (
    <div>
      <Head>
        <title>Anantha Krishnan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href=""/>
      </Head>
    <Navbar/>

      <div id="Home" className="bg-black text-red-600 text-3xl justify-around flex py-36 pb-28">
            <div className='flex flex-col lg:w-1/2 sm:w-screen'>
              <div className=' lg:ml-28 lg:mt-28 md:ml-28 md:mt-28 sm:ml-0 mt-0'>

                <p className='text-xl text-white'>Hey!<span>I'm&apos;</span></p>
                <h1 className='text-5xl text-white'>Anantha Krishnan</h1>
                <p className='text-xl mt-3 mb-3 text-white'>Self-Taught</p>
                <Typewriter
                    options={{
                        strings: ['Web Developer', 'App Developer','Digital Marketeer'],
                        autoStart: true,
                        loop: true,
                                }}
                />
            </div>
              </div>
            <div className='hidden sm:flex items-center w-1/2'>
            <Lottie 
	    options={defaultOptions}
        height={400}
        width={400}
      />

            </div>
         
           
                   
        </div>
       


<About/>
   <Work/>



      <Footer></Footer>




    </div>
  )
}
